pipeline:
  web:
    image: civicactions/fema-grants
    commands:
      - drush st

services:
  db:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=drupal
