workspace:
  base: /app
  path: src

pipeline:
  test:
    image: fema-grants:latest
    commands:
      - sleep 20
      - timeout 300 bash -c 'until curl -m1 -s http://web > /dev/null; do sleep 0.5; done'
      - drush --root=/app/src/docroot core:status
      - /app/src/vendor/bin/behat -c /app/src/tests/behat.yml
      - cd /app/src/web/core && phpunit --testsuite=unit --exclude-group=DependencyInjection,Composer
  slack:
    image: plugins/slack
    channel: proposal-fema
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]

services:
  db:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=drupal
  web:
    image: fema-grants:latest
