pipeline:
  web:
    image: civicactions/fema-grants
    commands:
      - su www-data -c'drush st'
      - su www-data -c'phpunit --testsuite=unit --exclude-group=DependencyInjection,Composer'

services:
  db:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=drupal
