workspace:
  base: /var
  path: www

pipeline:
  test:
    image: civicactions/fema-grants:latest
    commands:
      - sleep 20
      - timeout 300 bash -c 'until curl -m1 -s http://web > /dev/null; do sleep 0.5; done'
      - drush --root=/var/www/docroot core:status
      - /var/www/vendor/bin/behat -c /var/www/tests/behat.yml
      - cd /var/www/web/core && phpunit --testsuite=unit --exclude-group=DependencyInjection,Composer

services:
  db:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=drupal
  web:
    image: civicactions/fema-grants:latest

pipeline:
  slack:
    image: plugins/slack
    channel: proposal-fema
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
