version: '3'
services:
  pa11y:
    image: civicactions/docker-pa11y:latest
    volumes:
      - ./tests/accessibility:/home/node/app
    command: node pa11y.js
    cap_add:
      - SYS_ADMIN
    depends_on:
      - web
    networks:
      - web
networks:
  web:
